version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(module)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: app.log
    maxBytes: 10485760 # 10MB
    backupCount: 3
root:
  level: DEBUG
  handlers: [console, file]
loggers:
  sentence_transformers:
    level: INFO
    handlers: [ console ]
    propagate: no
  httpx:
    level: INFO
    handlers: [ console ]
    propagate: no
  fastapi:
    level: INFO
    handlers: [ console ]
    propagate: no
  root:
    level: INFO
    handlers: [ console ]
  qdrant_client:
    level: WARNING
    propagate: no